spring.application.name=crud
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.show-sql=true
spring.datasource.initialization-mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/postgresdb
spring.datasource.username=postgres
spring.datasource.password=example
spring.jpa.open-in-view=false